on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

